### ISSUE TITLE
Android: Toast Dialog sits at the very bottom of the page

### ISSUE THREAD

**Issue by kanayo** [triniwiz/nativescript-toasty#15]
Using the BOTTOM location, the toast rests right at the bottom of the page. 

Suggest providing a DEFAULT location which does not call SetGravity() and lets the OS position the toast.

**Comment by bradmartin** [comment]
v`1.4.0` contains a `NO_SETTING` enum value for positioning. https://github.com/triniwiz/nativescript-toasty/blob/master/demo/app/main-page.ts#L11
 On android this will let the OS default. On iOS it uses the default of the cocoapod which I believe is BOTTOM.

Didn't want to introduce a breaking change, so added the enum value for now. Next major release it can be dropped and the default of the position can be left to the OS/cocoapod.

**Comment by Whip** [comment]
This is not working in 3.0.0-alpha2. The toast is still at the very bottom along the edge. Why doesn't this use the default platform toasts? it looks like you built this from scratch.

**Comment by bradmartin** [comment]
On android it should be the platform widget, iOS doesn't have a native Toast, or if they do, it's fairly new addition to iOS. Which is why the POD is being used on iOS. As for building from scratch, nothing was from scratch except exposing everything in a simple API for those who aren't/won't figure out how to do the native API calls 😄 

If you'd like to submit a PR to fix something, I'm sure they'd be accepted if it's not breaking anything major.

**Comment by Whip** [comment]
On my phone (Nokia 6.1 Android 10) with default settings, the toast is displayed as a black rectangle at the bottom edge of the device.  While a regular toast is white and slightly transparent with rounded edges. Is this how its intended to be? See the image below for comparison.

![toasts](https://user-images.githubusercontent.com/11595460/76596598-93231780-6524-11ea-9759-d248f3ce4a6f.jpg)

**Comment by bradmartin** [comment]
That one on the right looks like the snackbar actually. That's odd but that's also Android so it's possible the device you're using maybe has a modified Android running where they've changed the defaults. Or possibly your app has some custom themes/styles where this is being modified. It's definitely not this plugin changing the look in that regard. You can view the Android source and verify that it's the Android toast widget always being created. So it's odd, but something in your app must be doing something to cause the toast to appear differently. I'd check for custom themes/styles in the Android libs being used and also how you're displaying the toast with the plugin API. Maybe some option does this.

**Comment by Whip** [comment]
Snackbars are usually full width but I agree, it looks similar. My device is an Android One device so I'm sure its stock android. Every other app sends toasts like the left image.

I'll run your demo app on my device in a few days and let you know how that looks. If it shows up normal, I'll have to figure out where the settings are being modified in my app because to my knowledge, I did not make any changes to the styles of toast.

**Comment by dangrima90** [comment]
@Whip did you ever get to solve the issue with the styling? I'm facing the exact same issue - I know it seems like a styling issue, however in my code there isn't anything overwriting the styling.

**Comment by Whip** [comment]
Nope. I don't have that phone anymore either.

**Comment by triniwiz** [comment]
@dangrima90 can you try replacing `.setGravity(android.view.Gravity.BOTTOM, xOffset, yOffset);` -> `.setGravity(android.view.Gravity.BOTTOM);` just wanna confirm something you will need to edit the code in node_modules

**Comment by dangrima90** [comment]
@triniwiz ended up going in a different direction and I'm not using the toast notification for this instance
