### ISSUE TITLE
Cannot find name 'Color' at nativescript-toasty/index.d.ts

### ISSUE THREAD

**Issue by Bhupendra123** [triniwiz/nativescript-toasty#20]
Following is log detail -
ERROR in node_modules/nativescript-toasty/index.d.ts(6,17): error TS2304: Cannot find name 'Color'.
node_modules/nativescript-toasty/index.d.ts(7,23): error TS2304: Cannot find name 'Color'.
node_modules/nativescript-toasty/index.d.ts(11,14): error TS2304: Cannot find name 'Color'.
node_modules/nativescript-toasty/index.d.ts(12,20): error TS2304: Cannot find name 'Color'.
node_modules/nativescript-toasty/index.d.ts(36,23): error TS2304: Cannot find name 'Color'.
node_modules/nativescript-toasty/index.d.ts(43,29): error TS2304: Cannot find name 'Color'.

This issue occurs for both 1.3.1 (last version) and 1.4.0 (latest version). I request you to please make stable version available for installation because there are many developers those using your plugin like me and they have to deliver their projects to their clients/customers.
In my case it is critical issue and it will take lot of time to replace Toasty by another plugin.

**Comment by bradmartin** [comment]
You can always fix it yourself if it's a blocking issue. Fork, use that dep or locally in your project. Or pay someone to fix it with the skills/knowledge. Even better would be a PR to fix. This is literally one line of code to fix the typings issue.

However, I am about to publish 2.0 which will be a breaking change since the major is changing (learn SEMVER if you're not sure what that means). This issue will be fixed in that release.

**Comment by bradmartin** [comment]
You can update to 2.0.0 which has the fix in the typings file. Or you can fix your issue locally in the `1.x` versions and run that for now if you don't want to update to the new API of the 2x version.
